version: 2
updates:
  # Bundler ecosystem - scan bundler folder but exclude exclude-me
  - package-ecosystem: "bundler"
    directory: "/bundler"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

  # Cargo ecosystem - scan cargo folder but exclude exclude-me
  - package-ecosystem: "cargo"
    directory: "/cargo"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

  # PNPM ecosystem - scan pnpm workspace but exclude exclude-me
  - package-ecosystem: "npm"
    directory: "/pnpm"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

  # Bun ecosystem - scan bun workspace but exclude exclude-me
  - package-ecosystem: "bun"
    directory: "/bun"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

 # Maven ecosystem - scan maven workspace but exclude exclude-me
  - package-ecosystem: "maven"
    directory: "/maven"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

  