version: 2
updates:
  # Bundler ecosystem - include only the include-me folder
  - package-ecosystem: "bundler"
    directory: "/bundler"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"

  # Cargo ecosystem - include only the include-me folder  
  - package-ecosystem: "cargo"
    directory: "/cargo"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "exclude-me/**"