[package]
name = "legacy-rust-app"
version = "0.9.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["full"] }
serde = { version = "1.0.143", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
