[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
tokio = { version = "1.21", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
