source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'thin', '~> 1.8'
gem 'json', '~> 2.6'
gem 'activesupport', '~> 7.0'
gem 'rake', '~> 13.0'
gem 'redis', '~> 4.8'

group :development do
  gem 'rerun', '~> 0.13'
  gem 'pry', '~> 0.14'
end

group :test do
  gem 'minitest', '~> 5.16'
  gem 'rack-test', '~> 2.0'
end
